<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(VftTargetFramework)</TargetFramework>
    <RootNamespace>VRCFaceTracking.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Gameloop.Vdf" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VRCFaceTracking.SDK\VRCFaceTracking.SDK.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="VRCFaceTracking.Core.Tests" />
  </ItemGroup>
</Project>