//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRCFaceTracking.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRCFaceTracking.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVANCED.
        /// </summary>
        public static string AdvancedSectionHeader {
            get {
                return ResourceManager.GetString("AdvancedSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRCFaceTracking.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance_Text {
            get {
                return ResourceManager.GetString("Appearance_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start when SteamVR is launched.
        /// </summary>
        public static string AutoStartSettings_Description {
            get {
                return ResourceManager.GetString("AutoStartSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start.
        /// </summary>
        public static string AutoStartSettings_Header {
            get {
                return ResourceManager.GetString("AutoStartSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch VRCFaceTracking automatically with SteamVR..
        /// </summary>
        public static string AutoStartSettingsTooltip {
            get {
                return ResourceManager.GetString("AutoStartSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamVR is not running. Start SteamVR to change this..
        /// </summary>
        public static string AutoStartSettingsUnavailableDescription {
            get {
                return ResourceManager.GetString("AutoStartSettingsUnavailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye.
        /// </summary>
        public static string CameraStreamsEye {
            get {
                return ResourceManager.GetString("CameraStreamsEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera streams.
        /// </summary>
        public static string CameraStreamsHeader {
            get {
                return ResourceManager.GetString("CameraStreamsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lip.
        /// </summary>
        public static string CameraStreamsLip {
            get {
                return ResourceManager.GetString("CameraStreamsLip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No camera image from this module..
        /// </summary>
        public static string CameraStreamsNone {
            get {
                return ResourceManager.GetString("CameraStreamsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for frames....
        /// </summary>
        public static string CameraStreamsWaiting {
            get {
                return ResourceManager.GetString("CameraStreamsWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brows.
        /// </summary>
        public static string CapabilityBrows {
            get {
                return ResourceManager.GetString("CapabilityBrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyes.
        /// </summary>
        public static string CapabilityEyes {
            get {
                return ResourceManager.GetString("CapabilityEyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string CapabilityHead {
            get {
                return ResourceManager.GetString("CapabilityHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth.
        /// </summary>
        public static string CapabilityMouth {
            get {
                return ResourceManager.GetString("CapabilityMouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tongue.
        /// </summary>
        public static string CapabilityTongue {
            get {
                return ResourceManager.GetString("CapabilityTongue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckUpdatesButtonContent {
            get {
                return ResourceManager.GetString("CheckUpdatesButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks for a newer release on GitHub.
        /// </summary>
        public static string CheckUpdatesDescription {
            get {
                return ResourceManager.GetString("CheckUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check now.
        /// </summary>
        public static string CheckUpdatesHeader {
            get {
                return ResourceManager.GetString("CheckUpdatesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask GitHub for a newer release right now..
        /// </summary>
        public static string CheckUpdatesTooltip {
            get {
                return ResourceManager.GetString("CheckUpdatesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string ContributorsHeader {
            get {
                return ResourceManager.GetString("ContributorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard..
        /// </summary>
        public static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy log to clipboard.
        /// </summary>
        public static string CopyLogButtonTooltip {
            get {
                return ResourceManager.GetString("CopyLogButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nerds who made this all possible &lt;3.
        /// </summary>
        public static string Credits_Description {
            get {
                return ResourceManager.GetString("Credits_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_Text {
            get {
                return ResourceManager.GetString("Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show logging and advanced settings. On by default for dev and beta builds..
        /// </summary>
        public static string DeveloperModeDescription {
            get {
                return ResourceManager.GetString("DeveloperModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer mode.
        /// </summary>
        public static string DeveloperModeHeader {
            get {
                return ResourceManager.GetString("DeveloperModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVELOPER.
        /// </summary>
        public static string DeveloperSectionHeader {
            get {
                return ResourceManager.GetString("DeveloperSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads_Text {
            get {
                return ResourceManager.GetString("Downloads_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close VRCFaceTracking when SteamVR shuts down. Off by default..
        /// </summary>
        public static string ExitWithSteamVrDescription {
            get {
                return ResourceManager.GetString("ExitWithSteamVrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit with SteamVR.
        /// </summary>
        public static string ExitWithSteamVrHeader {
            get {
                return ResourceManager.GetString("ExitWithSteamVrHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Tracking Active.
        /// </summary>
        public static string EyeTrackingActive_Text {
            get {
                return ResourceManager.GetString("EyeTrackingActive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Tracking Active.
        /// </summary>
        public static string FaceTrackingActive_Text {
            get {
                return ResourceManager.GetString("FaceTrackingActive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force VRCFT to unload and reinitialize all modules.
        /// </summary>
        public static string ForceReInitButton_Description {
            get {
                return ResourceManager.GetString("ForceReInitButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Re-Initialize.
        /// </summary>
        public static string ForceReInitButton_Header {
            get {
                return ResourceManager.GetString("ForceReInitButton_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces sending of all parameters every frame by forcing relevancy.
        /// </summary>
        public static string ForceRelevancyToggle_Description {
            get {
                return ResourceManager.GetString("ForceRelevancyToggle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Relevancy.
        /// </summary>
        public static string ForceRelevancyToggle_Header {
            get {
                return ResourceManager.GetString("ForceRelevancyToggle_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends every parameter regardless of whether the avatar uses it. Increases network traffic..
        /// </summary>
        public static string ForceRelevancyTooltip {
            get {
                return ResourceManager.GetString("ForceRelevancyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gremlin Mode.
        /// </summary>
        public static string GremlinModeToggleContent {
            get {
                return ResourceManager.GetString("GremlinModeToggleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocks actions that can break your setup..
        /// </summary>
        public static string GremlinModeTooltip {
            get {
                return ResourceManager.GetString("GremlinModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install from .zip.
        /// </summary>
        public static string InstallFromZipTooltip {
            get {
                return ResourceManager.GetString("InstallFromZipTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        public static string InstallStateAwaitingRestart {
            get {
                return ResourceManager.GetString("InstallStateAwaitingRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string InstallStateInstalled {
            get {
                return ResourceManager.GetString("InstallStateInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not installed.
        /// </summary>
        public static string InstallStateNotInstalled {
            get {
                return ResourceManager.GetString("InstallStateNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string InstallStateOutdated {
            get {
                return ResourceManager.GetString("InstallStateOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string LastUpdated_Text {
            get {
                return ResourceManager.GetString("LastUpdated_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Parameters.
        /// </summary>
        public static string LegacyParameters_Text {
            get {
                return ResourceManager.GetString("LegacyParameters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Test Avatar Detected.
        /// </summary>
        public static string LocalTestAvatar_Text {
            get {
                return ResourceManager.GetString("LocalTestAvatar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Test Avatars are not supported and will cause issues.
        /// </summary>
        public static string LocalTestAvatarTooltip_Content {
            get {
                return ResourceManager.GetString("LocalTestAvatarTooltip_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older log files are deleted when the app starts..
        /// </summary>
        public static string LogFilesToKeepDescription {
            get {
                return ResourceManager.GetString("LogFilesToKeepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files to keep.
        /// </summary>
        public static string LogFilesToKeepHeader {
            get {
                return ResourceManager.GetString("LogFilesToKeepHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older files are deleted at startup..
        /// </summary>
        public static string LogFilesToKeepTooltip {
            get {
                return ResourceManager.GetString("LogFilesToKeepTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        public static string LogFolderChangeContent {
            get {
                return ResourceManager.GetString("LogFolderChangeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log folder.
        /// </summary>
        public static string LogFolderHeader {
            get {
                return ResourceManager.GetString("LogFolderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - applies on next launch.
        /// </summary>
        public static string LogFolderPendingDescription {
            get {
                return ResourceManager.GetString("LogFolderPendingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose log folder.
        /// </summary>
        public static string LogFolderPickerTitle {
            get {
                return ResourceManager.GetString("LogFolderPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default.
        /// </summary>
        public static string LogFolderResetContent {
            get {
                return ResourceManager.GetString("LogFolderResetContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes effect the next time VRCFaceTracking starts..
        /// </summary>
        public static string LogFolderTooltip {
            get {
                return ResourceManager.GetString("LogFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGGING.
        /// </summary>
        public static string LoggingSectionHeader {
            get {
                return ResourceManager.GetString("LoggingSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved {0}..
        /// </summary>
        public static string LogSaved {
            get {
                return ResourceManager.GetString("LogSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save {0}..
        /// </summary>
        public static string LogSaveFailed {
            get {
                return ResourceManager.GetString("LogSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install failed.
        /// </summary>
        public static string ModuleActionFailed {
            get {
                return ResourceManager.GetString("ModuleActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string ModuleActionInstall {
            get {
                return ResourceManager.GetString("ModuleActionInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed..
        /// </summary>
        public static string ModuleActionInstalled {
            get {
                return ResourceManager.GetString("ModuleActionInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string ModuleActionInstalling {
            get {
                return ResourceManager.GetString("ModuleActionInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string ModuleActionUninstall {
            get {
                return ResourceManager.GetString("ModuleActionUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        public static string ModuleActionUninstalling {
            get {
                return ResourceManager.GetString("ModuleActionUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module process stopped unexpectedly.
        /// </summary>
        public static string ModuleCrashedText {
            get {
                return ResourceManager.GetString("ModuleCrashedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading capabilities.
        /// </summary>
        public static string ModuleInitStageCapabilities {
            get {
                return ResourceManager.GetString("ModuleInitStageCapabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string ModuleInitStageHandshake {
            get {
                return ResourceManager.GetString("ModuleInitStageHandshake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        public static string ModuleInitStageInitializing {
            get {
                return ResourceManager.GetString("ModuleInitStageInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out.
        /// </summary>
        public static string ModuleInitStageTimedOut {
            get {
                return ResourceManager.GetString("ModuleInitStageTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Page.
        /// </summary>
        public static string ModulePage_Text {
            get {
                return ResourceManager.GetString("ModulePage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item from the list..
        /// </summary>
        public static string ModuleRegistry_NoSelection_Text {
            get {
                return ResourceManager.GetString("ModuleRegistry_NoSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart modules.
        /// </summary>
        public static string ModuleRestartButtonContent {
            get {
                return ResourceManager.GetString("ModuleRestartButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting modules.
        /// </summary>
        public static string ModulesInitializingHeader {
            get {
                return ResourceManager.GetString("ModulesInitializingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string ModulesSectionHeader {
            get {
                return ResourceManager.GetString("ModulesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string ModuleTrackingAutomatic {
            get {
                return ResourceManager.GetString("ModuleTrackingAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string ModuleTrackingCustom {
            get {
                return ResourceManager.GetString("ModuleTrackingCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking data.
        /// </summary>
        public static string ModuleTrackingHeader {
            get {
                return ResourceManager.GetString("ModuleTrackingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to automatic.
        /// </summary>
        public static string ModuleTrackingResetContent {
            get {
                return ResourceManager.GetString("ModuleTrackingResetContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgs/sec Incoming.
        /// </summary>
        public static string msIncoming_Text {
            get {
                return ResourceManager.GetString("msIncoming_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgs/sec Outgoing.
        /// </summary>
        public static string msOutgoing_Text {
            get {
                return ResourceManager.GetString("msOutgoing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this mutation..
        /// </summary>
        public static string MutationActiveToggleTooltip {
            get {
                return ResourceManager.GetString("MutationActiveToggleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string MutationToggleOff {
            get {
                return ResourceManager.GetString("MutationToggleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string MutationToggleOn {
            get {
                return ResourceManager.GetString("MutationToggleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You appear to have no modules installed..
        /// </summary>
        public static string no_modules_installed_warning_Description {
            get {
                return ResourceManager.GetString("no_modules_installed_warning_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Modules Installed.
        /// </summary>
        public static string no_modules_installed_warning_Title {
            get {
                return ResourceManager.GetString("no_modules_installed_warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string OpenLogsButtonContent {
            get {
                return ResourceManager.GetString("OpenLogsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the log folder.
        /// </summary>
        public static string OpenLogsFolderButtonTooltip {
            get {
                return ResourceManager.GetString("OpenLogsFolderButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamVR.
        /// </summary>
        public static string OpenVrSectionHeader {
            get {
                return ResourceManager.GetString("OpenVrSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled..
        /// </summary>
        public static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination IP.
        /// </summary>
        public static string OscAddressLabel {
            get {
                return ResourceManager.GetString("OscAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where parameters are sent. Change only for a second PC..
        /// </summary>
        public static string OscAddressTooltip {
            get {
                return ResourceManager.GetString("OscAddressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Port (Legacy).
        /// </summary>
        public static string OscInPortLabel {
            get {
                return ResourceManager.GetString("OscInPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port VRChat sends to. Only used when OSCQuery is unavailable..
        /// </summary>
        public static string OscInPortTooltip {
            get {
                return ResourceManager.GetString("OscInPortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Port.
        /// </summary>
        public static string OscOutPortLabel {
            get {
                return ResourceManager.GetString("OscOutPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port VRChat listens on. 9000 unless you changed it..
        /// </summary>
        public static string OscOutPortTooltip {
            get {
                return ResourceManager.GetString("OscOutPortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC.
        /// </summary>
        public static string OscSectionHeader {
            get {
                return ResourceManager.GetString("OscSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where should OSC Data be sent?.
        /// </summary>
        public static string OscSettings_Description {
            get {
                return ResourceManager.GetString("OscSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC Address.
        /// </summary>
        public static string OscSettings_Header {
            get {
                return ResourceManager.GetString("OscSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC Status.
        /// </summary>
        public static string OSCStatus_Text {
            get {
                return ResourceManager.GetString("OSCStatus_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action failed..
        /// </summary>
        public static string OutputActionFailed {
            get {
                return ResourceManager.GetString("OutputActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-scroll.
        /// </summary>
        public static string OutputAutoScrollToggleContent {
            get {
                return ResourceManager.GetString("OutputAutoScrollToggleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string OutputClearButtonContent {
            get {
                return ResourceManager.GetString("OutputClearButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the log view.
        /// </summary>
        public static string OutputClearButtonTooltip {
            get {
                return ResourceManager.GetString("OutputClearButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string OutputCopyButtonContent {
            get {
                return ResourceManager.GetString("OutputCopyButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string OutputOpenFolderButtonContent {
            get {
                return ResourceManager.GetString("OutputOpenFolderButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string OutputSaveButtonContent {
            get {
                return ResourceManager.GetString("OutputSaveButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters_Text {
            get {
                return ResourceManager.GetString("Parameters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Initialize.
        /// </summary>
        public static string ReInitButton_Content {
            get {
                return ResourceManager.GetString("ReInitButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all VRChat OSC config data (will be regenerated when avatar is reloaded).
        /// </summary>
        public static string ResetAvatarConfButton_Description {
            get {
                return ResourceManager.GetString("ResetAvatarConfButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset VRChat Configs.
        /// </summary>
        public static string ResetAvatarConfButton_Header {
            get {
                return ResourceManager.GetString("ResetAvatarConfButton_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButton_Content {
            get {
                return ResourceManager.GetString("ResetButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all data stored by VRCFT in your AppData folder.
        /// </summary>
        public static string ResetVRCFTButton_Description {
            get {
                return ResourceManager.GetString("ResetVRCFTButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset VRCFT.
        /// </summary>
        public static string ResetVRCFTButton_Header {
            get {
                return ResourceManager.GetString("ResetVRCFTButton_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger, danger. High voltage...
        /// </summary>
        public static string RiskySettings_Description {
            get {
                return ResourceManager.GetString("RiskySettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risky Settings.
        /// </summary>
        public static string RiskySettings_Header {
            get {
                return ResourceManager.GetString("RiskySettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log to file.
        /// </summary>
        public static string SaveLogButtonTooltip {
            get {
                return ResourceManager.GetString("SaveLogButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Log.
        /// </summary>
        public static string SaveLogPickerTitle {
            get {
                return ResourceManager.GetString("SaveLogPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search modules.
        /// </summary>
        public static string SearchModulesWatermark {
            get {
                return ResourceManager.GetString("SearchModulesWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Shell_Main_Content {
            get {
                return ResourceManager.GetString("Shell_Main_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Registry.
        /// </summary>
        public static string Shell_ModuleRegistry_Content {
            get {
                return ResourceManager.GetString("Shell_ModuleRegistry_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Shell_Output_Content {
            get {
                return ResourceManager.GetString("Shell_Output_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Settings.
        /// </summary>
        public static string Shell_TrackingSettings_Content {
            get {
                return ResourceManager.GetString("Shell_TrackingSettings_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show developer settings.
        /// </summary>
        public static string ShowDeveloperSettingsContent {
            get {
                return ResourceManager.GetString("ShowDeveloperSettingsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusSectionHeader {
            get {
                return ResourceManager.GetString("StatusSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which app theme to display.
        /// </summary>
        public static string ThemeSettings_Description {
            get {
                return ResourceManager.GetString("ThemeSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        public static string ThemeSettings_Header {
            get {
                return ResourceManager.GetString("ThemeSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update to {0}?.
        /// </summary>
        public static string UpdateDialogContent {
            get {
                return ResourceManager.GetString("UpdateDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string UpdateDialogLater {
            get {
                return ResourceManager.GetString("UpdateDialogLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this version.
        /// </summary>
        public static string UpdateDialogSkip {
            get {
                return ResourceManager.GetString("UpdateDialogSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string UpdateDialogTitle {
            get {
                return ResourceManager.GetString("UpdateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateDialogUpdate {
            get {
                return ResourceManager.GetString("UpdateDialogUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update.
        /// </summary>
        public static string UpdateDownloadingTitle {
            get {
                return ResourceManager.GetString("UpdateDownloadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update could not be applied. See the log for details..
        /// </summary>
        public static string UpdateFailedContent {
            get {
                return ResourceManager.GetString("UpdateFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        public static string UpdateFailedTitle {
            get {
                return ResourceManager.GetString("UpdateFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for a new version when the app starts.
        /// </summary>
        public static string UpdatesDescription {
            get {
                return ResourceManager.GetString("UpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string UpdatesHeader {
            get {
                return ResourceManager.GetString("UpdatesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATES.
        /// </summary>
        public static string UpdatesSectionHeader {
            get {
                return ResourceManager.GetString("UpdatesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string UpdateUpToDateClose {
            get {
                return ResourceManager.GetString("UpdateUpToDateClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the newest {0} release..
        /// </summary>
        public static string UpdateUpToDateContent {
            get {
                return ResourceManager.GetString("UpdateUpToDateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available.
        /// </summary>
        public static string UpdateUpToDateTitle {
            get {
                return ResourceManager.GetString("UpdateUpToDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Instructions.
        /// </summary>
        public static string UsageInstructions_Text {
            get {
                return ResourceManager.GetString("UsageInstructions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Debug and Information lines to the log file. Warnings and errors are always written..
        /// </summary>
        public static string VerboseLoggingDescription {
            get {
                return ResourceManager.GetString("VerboseLoggingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on for dev and beta builds. Warnings and errors are always written..
        /// </summary>
        public static string VerboseLoggingForcedDescription {
            get {
                return ResourceManager.GetString("VerboseLoggingForcedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose logging.
        /// </summary>
        public static string VerboseLoggingHeader {
            get {
                return ResourceManager.GetString("VerboseLoggingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Much larger log files. Turn on before reproducing a bug..
        /// </summary>
        public static string VerboseLoggingTooltip {
            get {
                return ResourceManager.GetString("VerboseLoggingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version_Text {
            get {
                return ResourceManager.GetString("Version_Text", resourceCulture);
            }
        }
    }
}
